Name_of_Bag: inside_garden.bag # the name of the bag that supposed to be played
dir_to_global_map: /home/jessy104/ROS/LPTM_ROS/caoguangbiao.png # the location of the global map
checkpoint: /home/jessy104/ROS/LPTM_ROS/src/lptm_ros/checkpoints/checkpoint_cao_garden.pt

Basic:
 local_image_size: 360 # the sie of the local observation by elevation map (pixel)
 rotation: -178.0 # initial angle of the local map to be aligned to the global (degree)
 scale_ratio: 1.155 # initial scale of the local map to be aligned to the global (/)
 resolution: 0.05 # the resolution of the local map (m/pixel)

Odom_and_particles:
 start_location_odom_x: 89.3 
 start_location_odom_y: 52.5
 start_location_particle_x: 66
 start_location_particle_y: 38
 bag_start_time:  40 # the start time of the bag (s)
 odom_orientation: 4.0 # the orientation of the odometry from elevation map, by rotating following this angle, the orientation is aligned (degree)

Particle_covariance:
 number_of_particle: 2500
 X_Covariance: 0.20
 Y_Covariance: 0.20

Weight_param:
 B:
 W: